[package]
name = "ipov"
version = "0.1.0"
authors = ["Aditya Thakral <aditya.1998thakral@gmail.com>", "Archer Zhang <archer.xn@gmail.com>", "Peter Huang <peter.huang339@gmail.com>", "Winnie Ren <winnierjren@gmail.com>"]

[dependencies]
ears= {git = "https://github.com/jhasse/ears"}
